version: 2
updates:
  # Main project dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # Server dependencies
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    versioning-strategy: increase

  # Keep GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
