name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy Image Wasm
        run: npm run copy-wasm

      - name: Run linting
        run: npm run lint

      - name: Run stylelint
        run: npm run stylelint

      - name: Type check
        run: npm run type-check

      - name: Build Proxied Version
        run: npm run build-only

      - name: Move Proxied Build
        run: mv dist alpaca-web-proxied

      - name: Build Direct Version
        run: |
          VITE_APP_BASE_PATH=/html/ VITE_APP_DISCOVERY_MODE=direct npm run build-only

      - name: Move Direct Build
        run: mv dist alpaca-web-direct

      - name: Upload Proxied Build
        uses: actions/upload-artifact@v4
        with:
          name: alpaca-web-proxied
          path: alpaca-web-proxied/

      - name: Upload Direct Build
        uses: actions/upload-artifact@v4
        with:
          name: alpaca-web-direct
          path: alpaca-web-direct/

      - name: Run unit tests
        run: npm run test:unit
