name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy Image Wasm
        run: npm run copy-wasm

      - name: Build Proxied Version
        run: npm run build-only

      - name: Move Proxied Build
        run: mv dist alpaca-web-proxied

      - name: Build Direct Version
        run: |
          VITE_APP_BASE_PATH=/html/ VITE_APP_DISCOVERY_MODE=direct npm run build-only

      - name: Move Direct Build
        run: mv dist alpaca-web-direct

      - name: Zip Proxied Build
        run: zip -r alpaca-web-proxied-${{ github.ref_name }}.zip alpaca-web-proxied

      - name: Tar Proxied Build
        run: tar -czf alpaca-web-proxied-${{ github.ref_name }}.tar.gz alpaca-web-proxied

      - name: Zip Direct Build
        run: zip -r alpaca-web-direct-${{ github.ref_name }}.zip alpaca-web-direct

      - name: Tar Direct Build
        run: tar -czf alpaca-web-direct-${{ github.ref_name }}.tar.gz alpaca-web-direct

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            alpaca-web-proxied-${{ github.ref_name }}.zip
            alpaca-web-proxied-${{ github.ref_name }}.tar.gz
            alpaca-web-direct-${{ github.ref_name }}.zip
            alpaca-web-direct-${{ github.ref_name }}.tar.gz
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
